In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
dumy=pd.get_dummies(df.State)
dumy
xy=dumy.drop(['New York'],axis=1)
merge=pd.concat([df,xy],axis=1)
final=merge.drop(['State'],axis=1)
x=final.drop(['Profit'],axis=1)
x



R&D Spend  Administration  Marketing Spend  California  Florida
0   165349.20       136897.80        471784.10           0        0
1   162597.70       151377.59        443898.53           1        0
2   153441.51       101145.55        407934.54           0        1
3   144372.41       118671.85        383199.62           0        0
4   142107.34        91391.77        366168.42           0        1
5   131876.90        99814.71        362861.36           0        0
6   134615.46       147198.87        127716.82           1        0
7   130298.13       145530.06        323876.68           0        1
8   120542.52       148718.95        311613.29           0        0
9   123334.88       108679.17        304981.62           1        0
10  101913.08       110594.11        229160.95           0        1
11  100671.96        91790.61        249744.55           1        0
12   93863.75       127320.38        249839.44           0        1
13   91992.39       135495.07        252664.93           1        0
14  119943.24       156547.42        256512.92           0        1
15  114523.61       122616.84        261776.23           0        0
16   78013.11       121597.55        264346.06           1        0
17   94657.16       145077.58        282574.31           0        0
18   91749.16       114175.79        294919.57           0        1
19   86419.70       153514.11             0.00           0        0
20   76253.86       113867.30        298664.47           1        0
21   78389.47       153773.43        299737.29           0        0
22   73994.56       122782.75        303319.26           0        1
23   67532.53       105751.03        304768.73           0        1
24   77044.01        99281.34        140574.81           0        0
25   64664.71       139553.16        137962.62           1        0
26   75328.87       144135.98        134050.07           0        1
27   72107.60       127864.55        353183.81           0        0
28   66051.52       182645.56        118148.20           0        1
29   65605.48       153032.06        107138.38           0        0
30   61994.48       115641.28         91131.24           0        1
31   61136.38       152701.92         88218.23           0        0
32   63408.86       129219.61         46085.25           1        0
33   55493.95       103057.49        214634.81           0        1
34   46426.07       157693.92        210797.67           1        0
35   46014.02        85047.44        205517.64           0        0
36   28663.76       127056.21        201126.82           0        1
37   44069.95        51283.14        197029.42           1        0
38   20229.59        65947.93        185265.10           0        0
39   38558.51        82982.09        174999.30           1        0
40   28754.33       118546.05        172795.67           1        0
41   27892.92        84710.77        164470.71           0        1
42   23640.93        96189.63        148001.11           1        0
43   15505.73       127382.30         35534.17           0        0
44   22177.74       154806.14         28334.72           1        0
45    1000.23       124153.04          1903.93           0        0
46    1315.46       115816.21        297114.46           0        1
47       0.00       135426.92             0.00           1        0
48     542.05        51743.15             0.00           0        0
49       0.00       116983.80         45173.06           1        0

In [4]:
y=final.Profit.values
y=y.reshape(-1,1)
y




array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [5]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)

sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

y_train=sc.fit_transform(y_train)
y_test=sc.transform(y_test)
x_test=sc.transform(x_test)
lm.fit(x_train,y_train)
pred=lm.predict(x_test)


C:\Users\harshit\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\harshit\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\harshit\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DataConversionWarning: Data with input dtype uint8, float64 were all converted to float64 by StandardScaler.
  # This is added back by InteractiveShellApp.init_path()


In [6]:
pred

array([[-2.67600105],
       [-2.67598299],
       [-2.67598307],
       [-2.67602   ],
       [-2.67595493],
       [-2.67599302],
       [-2.67602252],
       [-2.67600363],
       [-2.67599436],
       [-2.67596141]])

In [7]:
lm.coef_

array([[ 0.88287881,  0.02103762,  0.11169671, -0.00846692, -0.01774882]])

In [8]:
lm.intercept_

array([1.69028494e-16])

In [9]:
df1=pd.DataFrame({'Actual':y_test,'predicted':pred})
df2=df1.head(5)
df2

ValueError: If using all scalar values, you must pass an index

In [ ]:
df2.plot(kind='bar',figsize=(10,8))
plt.grid(which='major', linestyle='-', linewidth='0.5', color='green')
plt.grid(which='minor', linestyle=':', linewidth='0.5', color='black')
plt.show()

In [ ]:
from sklearn.metrics import mean_squared_error

np.sqrt(mean_squared_error(y_test,pred))

In [ ]:
xn=pd.DataFrame(np.ones((50,1)))
merge2=pd.concat([xn,x],axis=1)
import statsmodels.formula.api as sm
sm=sm.OLS(endog=y,exog=merge2).fit()
sm.summary()


#x_2=x2.values
#y2=y.values

#import statsmodels.formula.api as sm

#x1=x2.exog
#y1=y.endog
#sm=sm.OLS(x1,y1)
#fit=sm.fit()
#fit.summary()
#0	R&D Spend	Administration	Marketing Spend	California	Florida
#x=np.append(arr=np.ones((50,1)).astype(int),values=x,axis=1)

#xn=pd.DataFrame(x)
#xn
#xn=pd.DataFrame()
#xn
#ols=sm.ols()
#ols

In [11]:
def gd(x,y):
    m=np.ones((x.shape[1],1))
    #=m.transpose()
    itera=5
    y = np.array(y)
    n1=len(x)
    #learning_rate=0.001
    c=np.ones(n1)
    
    for i in range(itera):
        
        cost=(1/n1)*((np.dot(y.transpose(),y))-(np.dot(np.dot(m.transpose(),x.transpose()),(2*y.reshape(-1,1))-(np.dot(x,m)))))
        #m= m+learning_rate*(2/n1)*np.dot(x.transpose(),(np.dot(x,m)-y.reshape(len(y),1)))
        m = m + (2/n1)*(np.dot(x.transpose(),(y.reshape(len(y),1)-np.dot(x,m))))*0.01
        print("m{},cost {}, iteration {}".format(m,cost,i))
    
        
        #print(cost,m)
m = gd(x_train,y_train)
                       
                   

m[[0.98114351]
 [0.97771054]
 [0.97878454]
 [0.99312153]
 [0.98532355]],cost [[3.28723783]], iteration 0
m[[0.96310507]
 [0.95604177]
 [0.95832931]
 [0.98610202]
 [0.97097004]],cost [[3.13317629]], iteration 1
m[[0.94585254]
 [0.93497402]
 [0.93860474]
 [0.97895273]
 [0.95692843]],cost [[2.98859848]], iteration 2
m[[0.929355  ]
 [0.91448829]
 [0.91958242]
 [0.97168439]
 [0.94318816]],cost [[2.85284067]], iteration 3
m[[0.91358273]
 [0.89456625]
 [0.90123507]
 [0.9643072 ]
 [0.92973905]],cost [[2.72528811]], iteration 4


In [ ]:
k=(np.dot(np.linalg.inv(np.dot(x_train.transpose(),x_train)),np.dot(x_train.transpose(),y_train)))
c=np.ones((len(x_train),1))
inter=(np.dot(np.linalg.inv(np.dot(c.transpose(),c)),np.dot(c.transpose(),y_train)))
inter

In [ ]:
lm.intercept_

In [ ]:
lm.intercept_

In [ ]:
y.shape

In [ ]:
z=(2*y.reshape(-1,1))-(np.dot(x,m))
z

In [ ]:
x_train